"""
tailor_cover_letter reasoner — v4 (defense-in-depth marginal filtering).

Change vs v3: now applies marginal-skill filtering to BOTH the resume
AND the ScoreResult before the LLM call. The score is generated by
score_match against the original (unfiltered) resume so the fit number
is accurate, but for content generation we strip mentions of marginal
skills from its lists and reasoning text. Otherwise the LLM picks up
"Docker" from score.matching_skills even though we removed it from
resume.skills.
"""
from __future__ import annotations

from src.llm.client import structured_complete
from src.schemas.resume import ParsedResume
from src.schemas.job import JobPosting, ScoreResult
from src.schemas.cover_letter import CoverLetter
from src.utils.resume_filters import (
    filter_marginal_skills,
    filter_marginal_from_score,
)


SYSTEM_PROMPT = """You are an experienced career writer helping a candidate apply to a specific job.
You will be given the candidate's parsed resume, the job posting, and a fit assessment.
Your job: write a tailored cover letter that a hiring manager would actually read past the first line.

# OUTPUT REQUIREMENTS

Structure: exactly 3 body paragraphs.

P1 — HOOK (2-3 sentences):
  Open with a CONCRETE FACT from the candidate's resume that is directly
  relevant to this job. The first 12 words must contain a real proper noun.
  No generic openers. No statements of intent.

  BAD examples:
    - "I am applying for the X position..."
    - "I am writing to express my interest..."
    - "Your role caught my attention because..."
    - "With a strong background in..."

  GOOD examples:
    - "Last year I shipped agentic-marketing-stack — a production GPT-4o + DALL-E pipeline running real client work — and your AI Engineer posting reads like the next iteration of that work."
    - "The Best Local Impact Award I won at Intuitive Surgical's 2025 AI Fair was for exactly the kind of supervised-learning diagnostic system your job posting describes."

P2 — EVIDENCE (3-5 sentences):
  Tie 2-3 specific resume facts to specific job requirements. Use verbs from
  resume bullets exactly. Mention proper nouns. Numbers when present in resume.

P3 — CLOSING (2-3 sentences):
  NOT a place to parrot the company's mission. Instead: one sentence
  connecting a PROVEN candidate strength to a SPECIFIC need; one sentence
  with a clear next step.

# HARD RULES

R1. NEVER invent facts.
R2. NEVER mention any skill, technology, framework, or tool that does NOT
    appear in the candidate's Skills section, project stacks, or experience
    bullets as provided to you. If you're tempted to mention something,
    verify it's in the input first. If not in the input, DO NOT mention it.
R3. NEVER inflate verbs.
R4. NEVER cite a metric unless verbatim in the resume.
R5. ALWAYS ground claims; list cited facts in `key_evidence_used`.
R6. NO empty intensifiers: "showcasing", "demonstrating", "highlighting",
    "leveraging my expertise", "passionate about", "excited to", "team player",
    "results-oriented", "proven track record", "synergies", "value-add",
    "would love the opportunity".
R7. NO restating the job description.
R8. NO addressing gaps.
R9. Match the candidate's actual seniority.

# TONE

Formal but human. Direct, confident, evidence-first.
"""


def _format_resume(resume: ParsedResume) -> str:
    parts = [
        f"# Candidate: {resume.full_name}",
        f"\n## Summary\n{resume.summary}",
        "\n## Experience",
    ]
    for exp in resume.experience:
        parts.append(f"\n### {exp.title} @ {exp.company} ({exp.start_date} – {exp.end_date})")
        for b in exp.bullets:
            parts.append(f"- {b}")
    if resume.projects:
        parts.append("\n## Projects")
        for p in resume.projects:
            parts.append(f"\n### {p.name}")
            if p.stack:
                parts.append(f"Stack: {', '.join(p.stack)}")
            parts.append(p.description)
            for b in p.bullets:
                parts.append(f"- {b}")
    if resume.awards:
        parts.append("\n## Awards")
        for a in resume.awards:
            parts.append(f"- {a}")
    parts.append("\n## Skills")
    for cat in resume.skills:
        parts.append(f"- {cat.name}: {', '.join(cat.items)}")
    return "\n".join(parts)


def _format_job(job: JobPosting) -> str:
    parts = [f"# Job: {job.title} @ {job.company}"]
    if job.location:
        parts.append(f"Location: {job.location}{' (remote)' if job.is_remote else ''}")
    parts.append(f"\n## Description\n{job.description}")
    if job.required_skills:
        parts.append(f"\n## Required skills: {', '.join(job.required_skills)}")
    return "\n".join(parts)


def _format_score(score: ScoreResult) -> str:
    parts = [
        f"# Fit Assessment",
        f"Score: {score.score}/100  ({score.verdict})",
        f"Reasoning: {score.reasoning}",
    ]
    if score.matching_skills:
        parts.append(f"\nStrengths to emphasize: {', '.join(score.matching_skills)}")
    if score.strengths:
        parts.append("\nSpecific fit points:")
        for s in score.strengths:
            parts.append(f"  - {s}")
    if score.missing_skills:
        parts.append(f"\nGaps (do NOT address these): {', '.join(score.missing_skills)}")
    return "\n".join(parts)


async def tailor_cover_letter(
    resume: ParsedResume,
    job: JobPosting,
    score: ScoreResult,
) -> CoverLetter:
    """Generate a tailored cover letter, with marginal skills filtered from BOTH inputs."""
    # Defense in depth — sanitize both inputs that mention skills.
    sanitized_resume = filter_marginal_skills(resume)
    sanitized_score = filter_marginal_from_score(score, resume)

    user_prompt = f"""Write a tailored cover letter for this candidate applying to this job.

{_format_resume(sanitized_resume)}

---

{_format_job(job)}

---

{_format_score(sanitized_score)}

---

Return a structured CoverLetter following the rules above. Mention ONLY
skills/technologies that appear in the candidate's resume above. Do not
infer or import skills from the job description.
"""
    return await structured_complete(
        schema=CoverLetter,
        system=SYSTEM_PROMPT,
        user=user_prompt,
    )
